### ISSUE TITLE
Having multiple HttpMethod attributes on a route breaks DefaultRoutMap

### ISSUE THREAD

**Issue by jamiecoh** [riskfirst/riskfirst.hateoas#3]
A controller with 2 HttpMethod attributes

```csharp
 [HttpPut(), HttpPatch(Name = "PatchModelRoute")]
public async Task<SomeModel> Update(...)
 { ... }
```

Generates the following error

```
System.Reflection.AmbiguousMatchException: Multiple custom attributes of the same type found.
   at System.Attribute.GetCustomAttribute(MemberInfo element, Type attributeType, Boolean inherit)
   at System.Reflection.CustomAttributeExtensions.GetCustomAttribute[T](MemberInfo element)
   at RiskFirst.Hateoas.DefaultRouteMap.<>c.<.ctor>b__5_4(<>f__AnonymousType0`2 m)
   at System.Linq.Enumerable.SelectEnumerableIterator`2.MoveNext()
   at System.Linq.Enumerable.WhereEnumerableIterator`1.MoveNext()
   at RiskFirst.Hateoas.DefaultRouteMap..ctor(IActionContextAccessor contextAccessor, ILogger`1 logger)
```

**Comment by jam13c** [comment]
Intention is to improve error handling aroundtransformation and raising a more meaningful error. I dont think anyone would want this situation to succeed (ie, give a partial link back) so errors during transformation will raise a `LinkTransformationException`.

**Comment by jamiecoh** [comment]
This should just work. I sometimes use Patch/Put on the same route
